import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    index("routes/home.tsx"),
    route("about", "routes/about.tsx"),
    route("contact", "routes/contact.tsx"),
    route("clients", "routes/clients.tsx"),
    route("career", "routes/career.tsx"),
    route("portfolio", "routes/portfolio.tsx"),
    route("web-development", "routes/web-development.tsx"),
    route("website-design", "routes/website-design.tsx"),
    route("graphic-design", "routes/graphic-design.tsx"),
    route("ecommerce", "routes/ecommerce.tsx"),
    route("privacy-policy", "routes/privacy-policy.tsx"),
    route("terms", "routes/terms.tsx"),
    route("video-editing", "routes/video-editing.tsx"),
    route("smart-analyzing", "routes/smart-analyzing.tsx"),
    route("agile-development", "routes/agile-development.tsx"),
    route("seamless-integration", "routes/seamless-integration.tsx"),
    route("continuous-optimization", "routes/continuous-optimization.tsx"),
    route("enhanced-productivity", "routes/enhanced-productivity.tsx"),
    route("scalability", "routes/scalability.tsx"),
    route("cost-efficient", "routes/cost-efficient.tsx"),
    route("availability", "routes/availability.tsx"),
    route("locations", "routes/locations.tsx"),
    route("locations/:city", "routes/location-detail.tsx"),
    route("promo", "routes/promo.tsx"),
] satisfies RouteConfig;
